name: AdventOfCode Stats

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  get_leaderboard:
    runs-on: ubuntu-latest
    outputs:
      leaderboard: ${{ steps.curl-leaderboard.outputs.leaderboard }}
    steps:
      - id: curl-leaderboard
        run: |
          echo "leaderboard=$(curl -s --cookie "session=${{ secrets.AOC_SESSION }}" ${{ secrets.AOC_LEADERBOARD }})" >> "$GITHUB_OUTPUT"

  extract_leaderboard_stats:
    needs: get_leaderboard
    runs-on: ubuntu-latest
    outputs:
      stars: ${{ steps.extract-stars.outputs.stars }}
      days_completed: ${{ steps.calculate-days-completed.outputs.days_completed }}
      days_attempted: ${{ steps.calculate-days-attempted.outputs.days_attempted }}
    steps:
    - id: extract-stars
      run: |
        echo "stars=$(jq '.members."${{ secrets.AOC_MEMBER_ID }}".stars' <<< '${{ needs.get_leaderboard.outputs.leaderboard }}')" >> "$GITHUB_OUTPUT"
    - id: calculate-days-completed
      run: |
        echo "days_completed=$(jq '.members."${{ secrets.AOC_MEMBER_ID }}".completion_day_level | map(select(has("1") and has("2"))) | length' <<< '${{ needs.get_leaderboard.outputs.leaderboard }}')" >> "$GITHUB_OUTPUT"
    - id: calculate-days-attempted
      run: |
        echo "days_attempted=$(jq '.members."${{ secrets.AOC_MEMBER_ID }}".completion_day_level | length' <<< '${{ needs.get_leaderboard.outputs.leaderboard }}')" >> "$GITHUB_OUTPUT"

  update_readme:
    needs: extract_leaderboard_stats
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch latest version"
        uses: actions/checkout@main
      - name: "Update README.md first line with recent data"
        run: |
          sed -i '1c# advent-of-code-2023 ![Days Attempted](https://img.shields.io/badge/Days%20Attempted-${{ needs.extract_leaderboard_stats.outputs.days_attempted }}-brightgreen) ![Days Completed](https://img.shields.io/badge/Days%20Completed-${{ needs.extract_leaderboard_stats.outputs.days_completed }}-brightgreen) ![AoC Stars](https://img.shields.io/badge/%E2%AD%90-${{ needs.extract_leaderboard_stats.outputs.stars }}-brightgreen) ![Made with Go](https://img.shields.io/badge/Made%20with-Go-%2300ADD8)' README.md
      - name: "Push changes"
        run: |
          git pull
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README badges"
          git push
