name: AdventOfCode Stats

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  get_leaderboard:
    name: "Get AdventOfCode leaderboard"
    runs-on: ubuntu-latest
    outputs:
      leaderboard: ${{ steps.curl-leaderboard.outputs.leaderboard }}
    steps:
      - id: curl-leaderboard
        run: |
          echo "leaderboard=$(curl -s --cookie "session=${{ secrets.AOC_SESSION }}" ${{ secrets.AOC_LEADERBOARD }})" >> "$GITHUB_OUTPUT"

  extract_leaderboard_stats:
    needs: get_leaderboard
    name: "Gets AdventOfCode leaderboard stats"
    runs-on: ubuntu-latest
    outputs:
      stars: ${{ steps.extract-stars.outputs.stars }}
      days_completed: ${{ steps.calculate-days-completed.outputs.days_completed }}
    steps:
    - id: extract-stars
      run: |
        echo "stars=$(echo ${{ needs.get_leaderboard.outputs.leaderboard }} | jq '.members."${{ secrets.AOC_MEMBER_ID }}".stars')" >> "$GITHUB_OUTPUT"
    - id: calculate-days-completed
      run: |
        echo "days_completed=$(echo ${{ needs.get_leaderboard.outputs.leaderboard }} | jq '.members."${{ secrets.AOC_MEMBER_ID }}".completion_day_level | map(select(has("1") and has("2"))) | length')" >> "$GITHUB_OUTPUT"

  update_readme:
    needs: extract_leaderboard_stats
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch latest version"
        uses: actions/checkout@main
      - name: "Update README.md first line with recent data"
        run: |
          sed '1c# advent-of-code-2023 ![Days Completed](https://img.shields.io/badge/Days%20Completed-${{ needs.extract_leaderboard_stats.outputs.days_completed }}-brightgreen) ![AoC Stars](https://img.shields.io/badge/%E2%AD%90-${{ needs.extract_leaderboard_stats.stars }}-brightgreen) ![Made with Go](https://img.shields.io/badge/Made%20with-Go-%2300ADD8)' README.md
      - name: "Push changes"
        run: |
          git config user.name github-actions
          git config.user.email github-actions@github.com
          git add README.md
          git commit -m "Update AOC badges"
          git push
